version: "3.8"
services:
  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,lambda,apigateway,dynamodb,rekognition
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1883:1883"